# Generated by Django 4.2.23 on 2025-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacion",
            name="ip_respuesta",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="mensaje_personalizado",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="mesa_asignada",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="plus_one",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="restricciones_alimentarias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
