# Generated by Django 4.2.23 on 2025-07-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0002_invitacion_ip_respuesta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitacion",
            name="ip_respuesta",
        ),
        migrations.RemoveField(
            model_name="invitacion",
            name="mensaje_personalizado",
        ),
        migrations.RemoveField(
            model_name="invitacion",
            name="mesa_asignada",
        ),
        migrations.RemoveField(
            model_name="invitacion",
            name="plus_one",
        ),
        migrations.RemoveField(
            model_name="invitacion",
            name="restricciones_alimentarias",
        ),
        migrations.RemoveField(
            model_name="invitacion",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="invitacion",
            name="fecha_boda",
            field=models.DateField(default="2026-02-21"),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="hora_boda",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="ubicacion_direccion",
            field=models.CharField(default="Av. Principal 123, Ciudad", max_length=300),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="ubicacion_maps_url",
            field=models.URLField(
                blank=True, help_text="URL de Google Maps", null=True
            ),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="ubicacion_nombre",
            field=models.CharField(
                default="Jardín de Eventos El Paraíso", max_length=200
            ),
        ),
    ]
