# Generated by Django 4.2.23 on 2025-07-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0003_remove_invitacion_ip_respuesta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionBoda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_novio", models.CharField(default="José", max_length=100)),
                ("nombre_novia", models.CharField(default="Jeovana", max_length=100)),
                (
                    "padre_novio_1",
                    models.CharField(
                        default="José Longino Mendoza Avilés", max_length=150
                    ),
                ),
                (
                    "padre_novio_2",
                    models.CharField(
                        default="Vanessa Vianeth Valdés Sánchez", max_length=150
                    ),
                ),
                (
                    "padre_novia_1",
                    models.CharField(
                        default="Gregorio Quirós Caballero", max_length=150
                    ),
                ),
                (
                    "padre_novia_2",
                    models.CharField(
                        default="Jeovana del Carmen Espinosa Montenegro", max_length=150
                    ),
                ),
                (
                    "historia_amor",
                    models.TextField(
                        default="Hace dos años, éramos dos desconocidos cuyos caminos se cruzaron por el destino. \n    Desde aquella primera cita llena de risas y emociones, nuestra historia ha sido un viaje lleno de amor y sueños compartidos."
                    ),
                ),
                (
                    "foto_preboda_1",
                    models.URLField(
                        blank=True,
                        help_text="URL de la primera foto de preboda",
                        null=True,
                    ),
                ),
                (
                    "foto_preboda_2",
                    models.URLField(
                        blank=True,
                        help_text="URL de la segunda foto de preboda",
                        null=True,
                    ),
                ),
                (
                    "foto_preboda_3",
                    models.URLField(
                        blank=True,
                        help_text="URL de la tercera foto de preboda",
                        null=True,
                    ),
                ),
                ("fecha_boda_default", models.DateField(default="2026-02-21")),
                ("hora_boda_default", models.TimeField(default="18:00")),
                (
                    "ubicacion_default",
                    models.CharField(
                        default="Jardín de Eventos El Paraíso", max_length=200
                    ),
                ),
                (
                    "direccion_default",
                    models.CharField(
                        default="Av. Principal 123, Ciudad", max_length=300
                    ),
                ),
                ("maps_url_default", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Configuración de la Boda",
                "verbose_name_plural": "Configuración de la Boda",
            },
        ),
    ]
