# Generated by Django 4.2.23 on 2025-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0004_configuracionboda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionboda",
            name="direccion_default",
            field=models.CharField(
                default="Av. 9a Oeste, David, Provincia de Chiriquí 507", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="configuracionboda",
            name="nombre_novia",
            field=models.CharField(default="Grace", max_length=100),
        ),
        migrations.AlterField(
            model_name="configuracionboda",
            name="ubicacion_default",
            field=models.CharField(
                default="Parroquia Sagrado Corazón de Jesús", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="invitacion",
            name="ubicacion_direccion",
            field=models.CharField(
                default="Av. 9a Oeste, David, Provincia de Chiriquí 507", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="invitacion",
            name="ubicacion_maps_url",
            field=models.URLField(
                blank=True,
                default="https://maps.app.goo.gl/9WFuwUWAHRs3yUSs9",
                help_text="URL de Google Maps",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitacion",
            name="ubicacion_nombre",
            field=models.CharField(
                default="Parroquia Sagrado Corazón de Jesús", max_length=200
            ),
        ),
    ]
