# Generated by Django 4.2.23 on 2025-07-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0005_alter_configuracionboda_direccion_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionboda",
            name="maps_url_default",
            field=models.URLField(
                blank=True,
                default="https://maps.app.goo.gl/9WFuwUWAHRs3yUSs9",
                null=True,
            ),
        ),
    ]
