# Generated by Django 4.2.23 on 2025-09-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0006_alter_configuracionboda_maps_url_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitacion",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
