# Generated by Django 4.2.23 on 2025-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0006_alter_configuracionboda_maps_url_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitacion",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Invitación",
                "verbose_name_plural": "Invitaciones",
            },
        ),
        migrations.AddField(
            model_name="invitacion",
            name="email_enviado",
            field=models.BooleanField(
                default=False, help_text="Si se ha enviado el email de invitación"
            ),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="fecha_ultimo_email",
            field=models.DateTimeField(
                blank=True, help_text="Fecha del último email enviado", null=True
            ),
        ),
        migrations.AddField(
            model_name="invitacion",
            name="numero_recordatorios",
            field=models.IntegerField(
                default=0, help_text="Número de recordatorios enviados"
            ),
        ),
    ]
