# Generated by Django 4.2.23 on 2025-10-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitaciones", "0006_alter_configuracionboda_maps_url_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacion",
            name="mesa",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
