
[providers]
python = "3.9"

[variables]
NIXPKGS_ALLOW_UNFREE = "1"

[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn boda_project.wsgi:application --bind 0.0.0.0:$PORT"